import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import CollectionCarousel from "@/components/Carousel/CollectionCarousel";
import TopPickCarousel from "@/components/Carousel/TopPickCarousel";
import Banner from "@/components/Banner/Banner";
import NewArrivalsCarousel from "@/components/Carousel/NewArrivalsCarousel";
import SquareBanner from "@/components/Banner/SquareBanner";
import TrendsSection from "@/components/TrendsSection";
import BrandOfTheWeekCarousel from "@/components/Carousel/BrandOfTheWeekCarousel";
import BestSellerCarousel from "@/components/Carousel/BestSellerCarousel";
import RewardSquareBanner from "@/components/Carousel/RewardSquareBanner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
       
        {children}
        <CollectionCarousel/>
        <TopPickCarousel/>
        <Banner/>
        <NewArrivalsCarousel/>
        <SquareBanner/>
        <TrendsSection/>
        <BrandOfTheWeekCarousel/>
        <BestSellerCarousel/>
        <RewardSquareBanner/>
        <Footer/>
        
      </body>
    </html>
  );
}
